config/routes.rb
Rubygamedev::Application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get '/auth/failure', to: 'sessions#auth_failure'

  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

  resources :users, only: [:create, :edit, :update]
  get '/account' => 'users#edit_current_user', as: :account

  resources :posts do
    member do
      put :vote
    end
  end

  resources :comments
  resources :tags

  resources :guides
  resources :guide_categories

  resources :guide_revisions do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :libraries
  resources :library_categories

  get 'about' => 'pages#about', as: :about_page

  # Short Links
  get ':id' => 'short_links#post', as: :post_short_link, constraints: { id: /\d+/ }
end

app/models/library.rb
class Library < ActiveRecord::Base
  belongs_to :category, class_name: 'LibraryCategory', foreign_key: "category_id"
  belongs_to :user
  validates :category, presence: true
  validates :user, presence: true

  after_create :notify_twitter

  # TODO: move this to background job
  def notify_twitter
    url = Rails.application.routes.url_helpers.library_url(self)
    $twitter_client.update("New Library: #{title} #{url}")
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :set_library_category, except: [:show, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.new
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)
    @library.user = current_user
    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render action: 'show', status: :created, location: @library }
      else
        format.html { render action: 'new' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :description, :website_url, :category_id)
    end

    def set_library_category
      @library_categories = LibraryCategory.all
    end
end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url %>
  </div>
  <div class="field">
    <%= f.label :category_id, 'Choose Category' %><br>
    <%= f.select :category_id, @library_categories.map { |lc| [lc.title, lc.id] }, {}, {class: 'form-control'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>
  Latest Libraries
  <%= link_to 'New Library', new_library_path, class: 'btn btn-primary pull-right' %>
  <%= link_to 'Suggest a New Category', new_library_category_path, class: 'btn btn-primary pull-right category-btn' %>
</h1>

<% @library_categories.each do |category| %>
    <h4><%= category.title %></h4>
  <table class="posts table">
    <tbody>
      <% category.libraries.each do |library| %>
        <tr>
          <td>
            <% if library.instance_of? Library %>
              <%= image_tag 'libraries.jpeg', alt: 'libraries', class: 'guide-xs pull-left show', width: 25 %>
            <% end %>
            <%= link_to library.name, library_path(library) %>
            <br><span class="text-muted">Submitted by <%= library.user.username %> on <%= library.created_at.strftime("%m/%d/%Y") %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"></p>

<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @library.description %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @library.website_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @library.category.title %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>