config/routes.rb
Rubygamedev::Application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get '/auth/failure', to: 'sessions#auth_failure'

  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

  resources :users, only: [:create, :edit, :update]
  get '/account' => 'users#edit_current_user', as: :account

  resources :posts do
    member do
      put :vote
    end
  end

  resources :comments
  resources :tags

  resources :guides
  resources :guide_categories

  resources :guide_revisions do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :libraries
  resources :library_categories

  get 'about' => 'pages#about', as: :about_page

  # Short Links
  get ':id' => 'short_links#post', as: :post_short_link, constraints: { id: /\d+/ }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  validates :title, presence: true
  after_create :notify_twitter
  after_save :create_tags_from_tag_string
  paginates_per 15

  has_many :votes
  has_many :voted_users, through: :votes, source: :user, class_name: 'User'

  scope :internal_post, -> { where(type: "InternalPost") }
  scope :external_post, -> { where(type: "ExternalPost") }

  def types
    %w(ExternalPost InternalPost)
  end

  def external_post?
    type == "ExternalPost"
  end

  def internal_post?
    type == "InternalPost"
  end

  def username
    logger.error 'Must be implemented by subclass'
    ''
  end

  def number_of_comments
    logger.error 'Must be implemented by subclass'
    0
  end

  def tags_string
    tags.map(&:title).join(", ")
  end

  def tags_string=(value)
    @tags_list = []
    value.strip.downcase.split(/, *| +/).each do |tag|
      @tags_list.push(tag.strip)
    end
    @tags_list = @tags_list.uniq
  end

  # Called after save
  def create_tags_from_tag_string
    return unless @tags_list.present?
    tags.clear
    @tags_list.each do |tag_title|
      existing_tag = Tag.find_by(title: tag_title)

      if existing_tag
        tags << existing_tag
      else
        tags.create!(title: tag_title, user_id: user_id)
      end
    end
  end

  def add_vote(user)
    Vote.find_or_create_by!(post_id: id, user_id: user.id)
  end

  def has_voted?(user)
    Vote.exists?(post_id: id, user_id: user.id)
  end

  def tweet_content
    url = Rails.application.routes.url_helpers.post_short_link_url(self, host: 'rbga.me')
    url = " #{url}"
    max_title_length = 140 - url.length
    title[0...max_title_length] + url
  end

  def notify_twitter
    if Rails.env.production?
      $twitter_client.update(tweet_content)
    end
  end

  def self.search(query)
    sql_query = <<-SQL
      SELECT * FROM posts
      WHERE posts.id IN (
        SELECT DISTINCT p.id
        FROM posts p
        LEFT JOIN comments c ON c.parent_id = p.id
        LEFT JOIN posts_tags pt ON pt.post_id = p.id
        LEFT JOIN tags t ON t.id = pt.tag_id
        WHERE (
              p.title LIKE :query
           OR p.body_markdown LIKE :query
           OR c.body LIKE :query
           OR t.title LIKE :query));
    SQL

    find_by_sql([sql_query, { query: "%#{query}%" }])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:search].present?
      @posts = Post.search(params[:search])
    else
      @posts = Post.all.order('created_at DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comment.parent = @post
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = InternalPost.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: post_path(@post) }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # raise "Sorry, you can't do that" unless current_user.admin?
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

   def vote
    @post = Post.find(params[:id])
    @post.add_vote(current_user)

    if request.xhr?
      render partial: 'votes/vote', locals: {post: @post}
    else
      flash[:notice] = "You have successfully voted"
      redirect_to(:back)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def post_type
    @type = params[:type] || "InternalPost"
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.

  def post_params
    params.require(post_type.underscore.to_sym).
      permit(:title, :body_markdown, :user_id, :tags_string)
  end
end

app/views/posts/_form.html.erb
<%= form_for(@post, url: (@post.new_record? ? posts_path : post_path(@post)), as: :internal_post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %>
        prohibited this post from being saved:
      </h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :body_markdown, "Body markdown" %>
    <%= f.text_area :body_markdown, class: 'form-control', rows: 5 %>
  </div>

  <div class="form-group tags-form">
    <%= f.label :tags_string, "Tags" %>
    <%= f.text_field :tags_string, class: 'form-control tags-input', autocomplete: 'off' %>
  </div>

  <%= f.submit nil, class: 'btn btn-default' %>
<% end %>

app/views/posts/_list.html.erb
<table class="posts table">
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <% if post.instance_of? Guide %>
            <%= image_tag 'Guide.png', alt: 'Guides', class: 'guide-xs pull-left show', width: 25 %>
          <% end %>

          <%= link_to post.title, post_path(post), class: 'post-link' %>

          <br><span class="text-muted">Submitted by <%= post.username %> on <%= post.created_at.strftime("%m/%d/%Y") %></span>
          <br><%= render 'posts/tags', post: post %>
        </td>
        <td>
          <%= render 'votes/vote', post: post %>
          <span class="badge pull-right" title="<%= pluralize(post.number_of_comments, 'comment') %>"><%= post.number_of_comments %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_post_summary.html.erb
<div class="post-summary">
  <% if @post.type == "Guide" %>
    <p>
      <h4>Category: <%= @post.category.name %></h4>
    </p>
  <% end %>

  <div class="body">
    <%= raw @post.body_html %>
    <% if @post.external_post? %>
      <p><%= link_to 'Visit Website', @post.source_url %></p>
    <% end %>
    <%= link_to "View post details", post_path(@post) %>
  </div>
</div>

app/views/posts/_tags.html.erb
<div class="tags">
  <% post.tags.each do |tag| %>
    <span><%= link_to tag.title, tag %></span>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>
  <% if params[:search].present? %>
    Post Search: "<%= params[:search] %>"
  <% else %>
    Latest Posts
  <% end %>
</h1>

<% if @posts.size == 0 %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <span>No result found</span>
  </div>
<% end %>

<%= render 'list' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :breadcrumbs do %>
  <ol class="breadcrumb">
    <li><%= link_to 'Posts', posts_path %></li>
    <li class="active"><%= @post.title %></li>
  </ol>
<% end %>

<div class="post">
  <h1>
    <%= @post.title %>
    <%= render 'votes/vote', post: @post %>
    <% if @post.instance_of? Guide %>
      <%= image_tag 'Guide.png', alt: 'Guides', class: 'guide-xs pull-left show', width: 25 %>
    <% end %> 
  </h1>

  <% if @post.type == "Guide" %>
    <p>
      <h4>Category: <%= @post.category.name %></h4>
    </p>
  <% end %>

  <p>
    Posted by: <%= @post.username %> on <%= @post.created_at.strftime("%m/%d/%Y") %>

    <% if policy(@post).update? %>
      <% if @post.type == "Guide" %>
        | <%= link_to 'Edit', edit_guide_path(@post) %>
      <% else %>
        | <%= link_to 'Edit', edit_post_path(@post) %>
      <% end %>
    <% else %>
        | <%= link_to 'Add Revision', new_guide_revision_path(guide_id: @post.id) %>
    <% end %>

    <% if policy(@post).destroy? %>
      | <%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <div class="body">
    <%= raw @post.body_html %>
    <% if @post.external_post? %>
      <p><%= link_to 'Visit Website', @post.source_url %></p>
    <% end %>
  </div>

  <%= render 'tags', post: @post %>

  <% unless @post.external_post? %>
    <h2>Comments</h2>
    <%= render 'comments/form' %>

    <% @post.comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  <% end %>
</div>