config/routes.rb
Rubygamedev::Application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get '/auth/failure', to: 'sessions#auth_failure'

  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

  resources :users, only: [:create, :edit, :update]
  get '/account' => 'users#edit_current_user', as: :account

  resources :posts do
    member do
      put :vote
    end
  end

  resources :comments
  resources :tags

  resources :guides
  resources :guide_categories

  resources :guide_revisions do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :libraries
  resources :library_categories

  get 'about' => 'pages#about', as: :about_page

  # Short Links
  get ':id' => 'short_links#post', as: :post_short_link, constraints: { id: /\d+/ }
end

app/models/guide.rb
class Guide < InternalPost
  belongs_to :category, class_name: 'GuideCategory', foreign_key: "guide_category_id"
  has_many :guide_revisions

  validates_presence_of :category
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]

  # GET /guide
  # GET /guide.json
  def index
    @guide_categories = GuideCategory.all
    @guides = Guide.all
    @guide_revisions = current_user.guide_revisions
  end

  # GET /guide/1
  # GET /guide/1.json
  def show
    @comment = Comment.new
    @comment.parent = @guide
  end

  # GET /guide/new
  def new
    @guide_categories = GuideCategory.all
    @guide = Guide.new(new_guide_params)
  end

  # GET /guide/1/edit
  def edit
    @guide_categories = GuideCategory.all
  end

  # POST /guide
  # POST /guide.json
  def create
    @guide_categories = GuideCategory.all
    @guide = Guide.new(guide_params)
    @guide.user = current_user

    respond_to do |format|
      if @guide.save
        format.html { redirect_to post_path(@guide), notice: 'Guide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @guide }
      else
        format.html { render action: 'new' }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guide/1
  # PATCH/PUT /guide/1.json
  def update
    authorize @guide
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to post_path(@guide), notice: 'Guide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /guide/1
  # DELETE /guide/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guide
    _url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    def new_guide_params
      if params[:guide]
        {guide_category_id: params[:guide][:guide_category_id]}
      else
        {}
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(
        :guide_category_id,
        :body_markdown,
        :user_id,
        :title,
        :tags_string)
    end
end

app/views/guides/edit.html.erb
<h1>Editing Guide</h1>

<%= form_for(@guide, url: (@guide.new_record? ? guides_path : guide_path(@guide))) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :guide_category_id, 'Choose Category' %>
    <%= f.select :guide_category_id, @guide_categories.map { |gc| [gc.name, gc.id] }, {}, {class: 'form-control'} %>

    <%= link_to 'New Category', new_guide_category_path, class: 'btn btn-primary btn-xs btn-new-category' %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :body_markdown %>
    <%= f.text_area :body_markdown, class: 'form-control', rows: 5 %>
  </div>

  <div class="form-group">
    <%= f.label :tags_string, "Tags" %>
    <%= f.text_field :tags_string, class: 'form-control' %>
  </div>

    <%= f.submit nil, class: 'btn btn-default' %>
<% end %>

app/views/guides/index.html.erb
<h1>
  Latest Guides
  <%= link_to 'New Guide', new_guide_path, class: 'btn btn-primary pull-right category-btn' %>
  <%= link_to 'Show All Categories', guide_categories_path, class: 'btn btn-primary pull-right category-btn' %>

  <% if current_user.admin? %>
    <%= link_to 'All Revisions', guide_revisions_path, class: 'btn btn-primary pull-right guide-rev-btn' %>
  <% else %>
    <%= link_to 'My Revisions', guide_revisions_path, class: 'btn btn-primary pull-right guide-rev-btn' %>
  <% end %>
</h1>

<% @guide_categories.select do |category| %>
  <% if category.guides.exists? %>
    <h4><%= category.name %></h4>
  <% end %>

  <table class="posts table">
    <tbody>
      <% category.guides.each do |post| %>
        <tr>
          <td>
            <% if post.instance_of? Guide %>
              <%= image_tag 'Guide.png', alt: 'Guides', class: 'guide-xs pull-left show', width: 25 %>
            <% end %>
            <%= link_to post.title, post_path(post) %>
            <br><span class="text-muted">Submitted by <%= post.username %> on <%= post.created_at.strftime("%m/%d/%Y") %></span>
            <br><%= render 'posts/tags', post: post %>
          </td>
          <td class="col-xs-1">
            <%= render 'votes/vote', post: post %>
            <span class="badge pull-right" title="<%= pluralize(post.number_of_comments, 'comment') %>"><%= post.number_of_comments %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/guides/new.html.erb
<h1>New Guide</h1>

<%= form_for(@guide, url: (@guide.new_record? ? guides_path : guide_path(@guide))) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :guide_category_id, 'Choose Category' %>
    <%= f.select :guide_category_id, @guide_categories.map { |gc| [gc.name, gc.id] }, {}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control input-lg' %>
  </div>

  <div class="form-group">
    <%= f.label :body_markdown %>
    <%= f.text_area :body_markdown, class: 'form-control', rows: 5 %>
  </div>

  <div class="form-group">
    <%= f.label :tags_string, "Tags" %>
    <%= f.text_field :tags_string, class: 'form-control' %>
  </div>

    <%= f.submit nil, class: 'btn btn-default' %>
<% end %>