config/routes.rb
Rubygamedev::Application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create_from_omniauth'
  get '/auth/failure', to: 'sessions#auth_failure'

  if Rails.env.development?
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

  resources :users, only: [:create, :edit, :update]
  get '/account' => 'users#edit_current_user', as: :account

  resources :posts do
    member do
      put :vote
    end
  end

  resources :comments
  resources :tags

  resources :guides
  resources :guide_categories

  resources :guide_revisions do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :libraries
  resources :library_categories

  get 'about' => 'pages#about', as: :about_page

  # Short Links
  get ':id' => 'short_links#post', as: :post_short_link, constraints: { id: /\d+/ }
end

app/models/guide_revision.rb
class GuideRevision < ActiveRecord::Base
  belongs_to :user
  belongs_to :guide, foreign_key: "original_guide_id"

  validates :user, :body_markdown, presence: :true
end

app/controllers/guide_revisions_controller.rb
class GuideRevisionsController < ApplicationController
  before_action :set_guide_revision, only: [:show, :edit, :update, :approve, :reject]
  before_action :require_login, except: [:index, :show]

  def index
    if current_user.admin?
      @guide_revisions = GuideRevision.where(status: nil)
      @approved_rejected_revisions = GuideRevision.where.not(status: nil)
      @approved_rejected_revisions = @approved_rejected_revisions.order("created_at desc")
    else
      @guide_revisions = GuideRevision.where(user_id: current_user.id)
    end

      @guide_revisions = @guide_revisions.order("created_at desc")
  end

  def new
    @guide_categories = GuideCategory.all
    @guide = Guide.find(params[:guide_id])
  end

  def show
    @guide_revision = GuideRevision.find(params[:id])
  end

  def create
    @guide = Guide.find(params[:guide_id])

    @guide_revision = GuideRevision.new(guide_params)
    @guide_revision.user = current_user
    @guide_revision.original_guide_id = @guide.id
    @guide_revision.save!

    respond_to do |format|
      if @guide_revision.save
        format.html { redirect_to guide_revisions_path(guide_id: @guide.id), notice: 'Your revision was successfully sent for review.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    authorize @guide_revision
    respond_to do |format|
      if @guide_revision.update(guide_revision_params)
        format.html { redirect_to guide_revision_path(@guide_revision), notice: 'Your revision was successfully updated.' }
      else
        format.html { render action: 'edit' }
        format.json { render json: @guide_revision.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    @guide = Guide.find(@guide_revision.original_guide_id)
    @guide.body_markdown = @guide_revision.body_markdown
    @guide.save!

    @guide_revision.status = 'approved'
    @guide_revision.save!

    redirect_to guide_revisions_path
  end

  def reject
    @guide_revision.status = 'rejected'
    @guide_revision.save!

    redirect_to guide_revisions_path
  end

  def edit
  end

  def set_guide_revision
    @guide_revision = GuideRevision.find(params[:id])
  end

  def guide_revision_params
    params.require(:guide_revision).permit(:title, :body_markdown)
  end

  def guide_params
    params.require(:guide).permit(:body_markdown)
  end
end

app/views/guide_revisions/edit.html.erb
<h1>Edit Guide Revision</h1>

<%= form_for(@guide_revision, url: (@guide_revision.new_record? ? guide_revison_path : guide_revision_path(@guide_revision))) do |f| %>
  <% if @guide_revision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide_revision.errors.count, "error") %> prohibited this guide_revision from being saved:</h2>

      <ul>
      <% @guide_revision.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body_markdown %>
    <%= f.text_area :body_markdown, class: 'form-control', rows: 5 %>
  </div>

    <%= f.submit "Update Revision", class: 'btn btn-default' %>
<% end %>

app/views/guide_revisions/index.html.erb
<h1>
  <% if current_user.admin? %>
    Pending Guide Revisions
  <% else %>
    My Guide Revisions
  <% end %>
</h1>

<table class="guide-revisions table">
  <thead>
    <tr>
      <th class="guide-h-t">Title</th>
      <th class="guide-t">Status</th>
      <th class="guide-t">Created</th>
    </tr>
  </thead>

  <tbody>
    <% @guide_revisions.each do |revision| %>
      <tr>
        <td class="col-md-6">
          <%= link_to revision.guide.title, revision, class: "guide-title-t" %>
        </td>
        <td>
          <% if policy(revision).view_status? %>
            <span class="revision-status pull-right">
              <% if revision.status == 'approved' %>
                <span class="status-a">Approved</span>
              <% elsif revision.status == 'rejected' %>
                <span class="status-r">Rejected</span>
              <% else %>
                <span class="status-p">Pending</span>
              <% end %>
            </span>
          <% end %>
        </td>
        <td class="date-n-time">
          <%= revision.created_at.strftime("%d %b %Y, %H:%M") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table><br/>

<% if current_user.admin? %>
  <h1>Approved/Rejected Revisions</h1>
  <table class="guide-revisions table">
    <thead>
      <tr>
        <th class="guide-h-t">Title</th>
        <th class="guide-t">Status</th>
        <th class="guide-t">Created</th>
      </tr>
    </thead>

    <tbody>
      <% @approved_rejected_revisions.each do |revision| %>
        <tr>
          <td class="col-md-6">
            <%= link_to revision.guide.title, revision, class: "guide-title-t" %>
          </td>

          <td>
            <% if policy(revision).view_status? %>
              <span class="revision-status pull-right">
                <% if revision.status == 'approved' %>
                  <span class="status-a">Approved</span>
                <% elsif revision.status == 'rejected' %>
                  <span class="status-r">Rejected</span>
                <% end %>
              </span>
            <% end %>
          </td>

         <td class="date-n-time">
            <%= revision.created_at.strftime("%d %b %Y, %H:%M") %>
         </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/guide_revisions/new.html.erb
<h1>New Guide Revision</h1>

<%= form_for @guide, url: guide_revisions_path(guide_id: @guide.id), method: :post do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :body_markdown %>
    <%= f.text_area :body_markdown, class: 'form-control', rows: 5 %>
  </div>

  <%= f.submit "Send for Review", class: 'btn btn-default' %>
<% end %>

app/views/guide_revisions/show.html.erb
<h1>
  <%= @guide_revision.guide.title %>
  <div class="admin-btn">
    <% if current_user.admin? %>
      <%= link_to 'All Revisions', guide_revisions_path, class: 'btn btn-primary guide-rev-btn' %>
      <%= link_to "Reject", reject_guide_revision_path(@guide_revision), method: 'PATCH', class: "btn btn-warning guide-rev-btn pull-right" %>
      <%= link_to "Approve", approve_guide_revision_path(@guide_revision), method: 'PATCH', class: "btn btn-success guide-rev-btn pull-right" %>
    <% end %>
  </div>
</h1>

<div class="guide-rev">
  <% if current_user && (current_user.id == @guide_revision.user_id) %>
    <span class="revision-status">
      <span class="guide-status">Status:</span>
      <% if @guide_revision.status == 'approved' %>
        <span class="status-a">Approved</span>
      <% elsif @guide_revision.status == 'rejected' %>
        <span class="status-r">Rejected</span>
      <% else %>
        <span class="status-p">Pending</span>
        <% if current_user.id == @guide_revision.user.id %>
          <%= link_to 'Edit revision', edit_guide_revision_path(@guide_revision), class: "btn btn-primary guide-rev-btn pull-left" %>
        <% end %>
      <% end %>
      <span>
        <%= link_to 'My Revisions', guide_revisions_path, class: "btn btn-primary guide-rev-btn pull-right" %>
      </span>
    </span>
  <% end %>
</div>


<div class="rev-body"><%= @guide_revision.body_markdown %></div>